# Generated by Django 6.0.1 on 2026-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attacking_armies_starting", models.IntegerField()),
                ("defending_armies_starting", models.IntegerField()),
                ("attacking_armies_remaining", models.IntegerField()),
                ("defending_armies_remaining", models.IntegerField()),
                ("result_statement", models.CharField(max_length=20)),
            ],
        ),
    ]
