# Generated by Django on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="timestamp",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
